### PR TITLE
Adding media player selection to the settings menu (part of Menus #54)

### PR DESCRIPTION
**Pull request by jrutanen**
Menus #54
- Added tabs and new menu item in settings.
- Fixed issues found by ochurlaud.
- Added new function to handle the database upgrade.

Wrong SQLite data type in config table #122
- Changed INTERGER to INTEGER

### CODE REVIEW

**Comment by ochurlaud** [comment]
Ok everything worked well this time.  I see you changed the git name, which is perfect. I still want to check the code, but as far as I've seen it's ok.

2 improvements still:
* if the program is not chosen, the default one should be used. 
* Linux filters for programs don't work (in the browse window)

**Comment by ochurlaud** [comment]
in ` DatabaseManager::addMediaPlayerPath(QString mediaPlayerPath)`

Why don't you directly remove and, if the string is not empty, insert? Here you've got a lot of logic (get the value, compare, update or insert depending of the state...).

**Comment by ochurlaud** [comment]
It's alright

**Comment by jrutanen** [comment]
You're right the addition is too complicated. Remove+insert is much more straight forward. I'll change that.

**Comment by jrutanen** [comment]
Thanks for a lot for the review.

**Pull request merged**
